ci:
  collect:
    numberOfRuns: 1
    startServerCommand: astro preview
    url:
      - http://localhost:4321/
      - http://localhost:4321/post
      - http://localhost:4321/post/rendering-pattern/ # Complex post demo
      - http://localhost:4321/toolbox
      - http://localhost:4321/shortpost

  assert:
    preset: 'lighthouse:no-pwa'
    assertions:
      csp-xss: 'warn'
      total-byte-weight: 'off' # TODO: enable this when this bug is fixed: https://github.com/GoogleChrome/lighthouse-ci/issues/1001
      identical-links-same-purpose: 'off'
      landmark-one-main: 'off'
      color-contrast: 'warn' # WCAG contrast might not be useful now, wait for WCAG3 or APCA?
      image-size-responsive: 'warn' # Some pages use external image that cannot be controlled
      non-composited-animations: 'warn'
      offscreen-images: 'warn' # Optional Optimization
      bf-cache: 'warn' # Optional Optimization
      uses-rel-preconnect: 'warn' # Optional Optimization
      unused-css-rules: 'warn' # Optional Optimization

  upload:
    target: 'temporary-public-storage'
    # upload options here

  server:
    # server options here

  wizard:
    # wizard options here
