name: Setup playwright

runs:
  using: composite
  steps:
    - name: Install Playwright
      run: pnpm add -D @playwright/test@latest
      shell: bash

    - name: Install Playwright Browsers
      run: pnpm dlx playwright install --with-deps
      shell: bash
